# Generated by Django 4.2.7 on 2023-11-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='alarm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
